name: Pipeline

on:
  push:
    branches: [ main ]
    paths: 
      - Chapter15/**
      - .github/workflows/pipeline.yaml
  workflow_dispatch:

env:
  ACRNAME: ${{ secrets.ACR_NAME }}

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"
          echo "ACR Name: ${{ secrets.ACR_NAME }}"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"}'

      - name: ACR login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./Chapter15
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/website/website:${{ github.run_number }}
